# Generated by Django 5.0.2 on 2024-02-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('createdby', models.CharField(max_length=45)),
                ('Project', models.CharField(max_length=45)),
            ],
        ),
    ]
